### PR TITLE
Replace Win64 attribute with Bitness attribute

### PR DESCRIPTION
**Pull request by robmen**

### CODE REVIEW

**Comment by rseanhall** [comment]
I think all of the Burn ones need to be defaulted to `always32` if `Win64` wasn't specified because that's the behavior you got when building a v3 "x64" bundle.

**Comment by robmen** [comment]
No. I don't want to push this attribute where no one had `Win64` before.

**Comment by rseanhall** [comment]
Then it should show a warning that there was a breaking change, right? I guess I've misunderstood the point of `wix convert`.

**Comment by robmen** [comment]
We could definitely add an error in WiX v3.14 to fail Bundle builds when the architecture is set to `x64` (probably should have been all along). All sorts of things are going to be a surprise when v4 suddenly starts running a 64-bit built-bundle in a 64-bit process. The immediate solution will be to change their build process to build a 32-bit bundle. No need to clutter up their code with `always32` when the correct thing will happen in that case. Then, when they think about moving forward to actually having a 64-bit bundle, they can move forward making decisions about which registry searches and approved for elevation executables need to be forced to `always32`.

**Comment by rseanhall** [comment]
I guess that works, it's just not something we've done before.

**Comment by rseanhall** [comment]
Actually, I should have been using `ARM64` as the example because people are using that today and will face breaking changes when moving to v4.

**Comment by robmen** [comment]
Hmm, looks like the v3 Util extension didn't correctly switch on the Compiler's platform (and neither did v4 until I just fixed it). I think that will mean that RegistrySearches have to be forced to `always32` if `Win64` wasn't set. However, `ApprovedExeForElevation` should be fine since it correctly follows the Compiler's platform.

**Comment by rseanhall** [comment]
I'm a little confused about this since we discussed it in the meeting. None of Burn's usage of Win64 followed the -arch setting, and I thought Bob and I both said we wanted to keep it that way.

**Comment by robmen** [comment]
`ApprovedExeForElevation` followed the `-arch` switch. The inconsistency is tripping me up. I'll open a new issue to rehash it (and if I end up agreeing with you guys) and will track changing the RegistrySearch code to go back to being inconsistent.

**Comment by rseanhall** [comment]
I don't understand how `ApprovedExeForElevation` followed the `-arch` switch, especially since I'm the one that implemented it by copying the code from `util:RegistrySearch`. It did the same thing the Util extension did: `YesNoType win64 = YesNoType.NotSet`.

**Comment by robmen** [comment]
Yeah, you're right. All busted.

**Pull request merged**
