### PR TITLE
Fix for added elements to reference platform-specific extension custo…

### PR DESCRIPTION
**Pull request by barnson**
…m actions.

### CODE REVIEW

**Comment by rseanhall** [comment]
@barnson Looking forward to getting the auto merge working?

**Comment by barnson** [comment]
Much easier to just go back to a monorepo.

**Comment by rseanhall** [comment]
Is this supposed to be merged?

**Comment by cpuwzd** [comment]
@barnson @robmen @rseanhall 

Is someone going to merge this so I can get my pull request ready to go?

@cpuwzd

**Comment by robmen** [comment]
@cpuwzd Why does this PR block your PR? Do you depend on something in it? If not, yours could go first.

**Pull request merged**
